# MediaWiki with MariaDB
#
# Access via "http://localhost:9002"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: "3"
services:
  mediawiki:
    image: mediawiki
    restart: always
    container_name: rho-wiki
    ports:
      - 9002:80
    volumes:
      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the LocalSettings line and use compose to restart
      # the mediawiki service
      - /var/www/html/images
      #- ./LocalSettings.php:/var/www/html/LocalSettings.php
    links:
      - database
  database:
    image: mariadb
    restart: always
    container_name: rho-wikidb
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
